[theme]
base = "light"
primaryColor = "#6c3ef5"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafaff"
textColor = "#111827"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
